### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Tagadda**

### CODE REVIEW

**Comment by Tagadda** [comment]
!testme

**Review by tituspijean — APPROVED** [review]
Pending CI test, but I agree with the fix. I basically did the same to install it on my server.

**Comment by Tagadda** [comment]
CI fails...
```
95618 WARNING /usr/share/yunohost/helpers.d/php: line 237: php-fpm7.4: command not found
```
Huh... shouldn't it be `php7.4-fpm` ? :confused:

**Comment by Tagadda** [comment]
!testme

**Pull request merged**
